language: python

sudo: false

notifications:
  email: false

os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

env:
  - CC=gcc-4.9
  - CXX=g++-4.9

python:
  - "3.6"

install:
  - python setup.py build_ext --force --inplace

script:
  - pytest
